name: build and deploy
on:
  pull_request:
    - opened
    - closed
  worflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: GetCodes
      uses: actions/checkout@v3
    - name: InstallS/w
      uses: actions/setup-node@v3
      with:
          node-version: 18
    - name: Install Dependnecies
      run: npm ci
    - name: Lint
      run: npm run lint
  
  Test:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
    - name: GetCodes
      uses: actions/checkout@v3
    - name: InstallS/w
      uses: actions/setup-node@v3
      
    - name: Install Dependnecies
      run: npm ci
    - name: Test
      run: npm run test
    - name: Details
      run: ${{ toJSON(github.event) }}
